for i in range(0,21):
    if i%2==0:
        print(i)

In [2]:
for i in range(4):
    for j in range(4):
        print("i=",i,"j=",j)

i= 0 j= 0
i= 0 j= 1
i= 0 j= 2
i= 0 j= 3
i= 1 j= 0
i= 1 j= 1
i= 1 j= 2
i= 1 j= 3
i= 2 j= 0
i= 2 j= 1
i= 2 j= 2
i= 2 j= 3
i= 3 j= 0
i= 3 j= 1
i= 3 j= 2
i= 3 j= 3


In [10]:
for i in range(1,5):
    for j in range(1,i+1):
        print("*",end=" ")
    print()

* 
* * 
* * * 
* * * * 


In [12]:
for i in range(10):
    if i==7:
        print("lets break after 7")
        break
    print(i)

0
1
2
3
4
5
6
lets break after 7


In [14]:
list=(100,200,300,400,500,600,700)
for i in list:
    if i>=500:
        print("anything above 500 be insured")
        break
    print(i)    

100
200
300
400
anything above 500 be insured


In [19]:
dict1={"H":"hydrogen","N":"nitrogen"}
dict1["N"]

'nitrogen'

In [79]:
for i in range(0,4):
    for j in range(0,4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print()        
        
    

      * 
    * * 
  * * * 
* * * * 


In [5]:
name=input("enter the string:")
for i in range(len(name)):
    for j in range(0,i+1):
        print(name[i],end=" ")
    print(" ")

enter the string:nireeksha
n  
i i  
r r r  
e e e e  
e e e e e  
k k k k k k  
s s s s s s s  
h h h h h h h h  
a a a a a a a a a  


In [4]:
rec={ }
n=int(input("enter number of students"))
i=1
while i<=n:
    name=input("enter student name:")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
print("name of the student","\t","% of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])
print(rec)    

enter number of students3
enter student name:navya
enter % marks of student60
enter student name:nireeksha
enter % marks of student70
enter student name:anusha
enter % marks of student80
name of the student 	 % of marks
	 navya 		 60
	 nireeksha 		 70
	 anusha 		 80
{'navya': '60', 'nireeksha': '70', 'anusha': '80'}


In [5]:
d={100:"hello",200:"mite",300:"navya"}
len(d)

3

In [6]:
len(rec)

3

In [10]:
word=input("enter sentence:")
d={}
for i in word:
    d[i]=d.get(i,0)+1
for k,v in d.items():
    print(k,"occurs",v,"times")

enter sentence:hi hello
h occurs 2 times
i occurs 1 times
  occurs 1 times
e occurs 1 times
l occurs 2 times
o occurs 1 times


In [11]:
word=input("enter sentence:")
d={}
for i in word:
    if i=='a'or i=='e'or i=='i'or i=='o'or i=='u':
        d[i]=d.get(i,0)+1
for k,v in d.items():
    print(k,"occurs",v,"times")

enter sentence:hellohello
e occurs 2 times
o occurs 2 times


In [14]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [15]:
print(n.index(5))

4


In [16]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [18]:
n=[1,2,3,4,5]
n2=[9,8,7,6,9]
n.extend(n2)
print(n)

[1, 2, 3, 4, 5, 9, 8, 7, 6, 9]


In [19]:
n.remove(2)

In [20]:
print(n)

[1, 3, 4, 5, 9, 8, 7, 6, 9]


###remove

### remove

In [21]:
n.pop()
print(n)

[1, 3, 4, 5, 9, 8, 7, 6]


In [22]:
n.reverse()
print(n)

[6, 7, 8, 9, 5, 4, 3, 1]


In [24]:
list1=['navya','nirikshit','pavan','anusha']
list1.sort()
print(list1)

['anusha', 'navya', 'nirikshit', 'pavan']


In [25]:
list1=['navya','nirikshit','pavan','anusha',1,2,3]
list1.sort()
print(list1)

TypeError: '<' not supported between instances of 'int' and 'str'

In [28]:
list1=['navya','nirikshit','pavan','anusha']
list1.sort(reverse=True)
print(list1)

['pavan', 'nirikshit', 'navya', 'anusha']


In [29]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [30]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [31]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [32]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)


[10, 20, 30, 40, 50, 60]


In [33]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [35]:
x=["mite","mangalore","nitte"]
y=["mite","managlore","nitte"]
x=y
x!=y
z=["mite","mangalore","nitte"]
x==z

False

In [36]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]
m.clear()
print(4 in n)

True


In [37]:
s=[2**x for x in range(1,6)]
print(s)


[2, 4, 8, 16, 32]


In [38]:
words=["mite","mysore","navya"]
l=[w[0] for w in words]
print(l)

['m', 'm', 'n']


In [44]:
def prime_no(num):
    if num==2:
        print("prime")
        exit()
    f=0    
    for i in range(2,num):
        if num%i==0:
            print("not prime no")
            f=1
            break
    if f==0:
        print("prime")
        
num=int(input("enter num:"))
prime_no(num)

enter num:3
prime


In [45]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [46]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))


[2, 4]

In [47]:
import numpy as np
my_list=[1,2,3]
my_list


[1, 2, 3]

In [48]:
np.array(my_list)

array([1, 2, 3])

In [49]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [54]:
np.zeros(3)

array([0., 0., 0.])

In [55]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [58]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [60]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [61]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
np.random.rand(2)

array([0.97942402, 0.42246153])

In [64]:
np.random.rand(5,5)

array([[0.73886533, 0.22596713, 0.22036294, 0.88035149, 0.97433358],
       [0.93830574, 0.43804355, 0.27897619, 0.67239618, 0.32696631],
       [0.19862117, 0.54076253, 0.95869931, 0.45086084, 0.40246948],
       [0.61006114, 0.22883485, 0.92076195, 0.33545592, 0.04819451],
       [0.34922862, 0.59161796, 0.45790231, 0.03089702, 0.87450411]])

In [65]:
np.random.randn(5,5)

array([[ 0.61915562, -1.07786145, -0.00901396, -0.3180846 , -1.51351429],
       [ 0.30863207,  0.13760554,  0.88379358, -0.08679501,  0.81879915],
       [ 0.22249475,  1.78985151, -0.62068123,  0.74110475,  0.49248713],
       [ 0.4512849 , -0.86172387, -0.51452728, -2.19746297,  0.33008534],
       [-0.78007105,  0.64447863,  0.7321596 , -0.2041688 , -1.31556371]])

In [66]:
np.random.randint(1,100,10)

array([85, 70, 82, 55, 45, 55, 59, 13,  6, 77])

In [67]:
ar=np.random.randint(1,100,10)
print(ar)

[ 9 51 93 34 44 54 36 41 13 12]


In [68]:
arr=np.arange(25)
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
runarr.max()

40

In [70]:
runarr.argmax()

4

In [71]:
runarr.min()

1

In [72]:
runarr.argmin()

2

In [73]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [74]:
arr.reshape(1,25).shape

(1, 25)

In [75]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

In [77]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
arr/arr

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
1/arr

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [80]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [81]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [83]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [84]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [85]:
np.log(arr)

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [86]:
arr=np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[8]

8

In [89]:
arr[1:5]

array([1, 2, 3, 4])

In [90]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [93]:
arr[0:5]=100

In [94]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [95]:
arr=np.arange(0,11)

In [96]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [98]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [100]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
arr[0:5]=5

In [119]:
arr=np.arange(0,10)
arr[0:10]=5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [120]:
arr=np.arange(10,80,2)

In [121]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [124]:
arr=np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
np.random.randn(25)

array([-1.17775052, -0.76892954,  0.30143644, -0.15104739,  0.50563037,
        0.21847885,  0.55896399, -0.12861378,  0.45342129,  0.28057347,
       -0.78057966, -0.92320028,  1.08468239,  0.4706243 ,  0.99491974,
        0.16183689, -0.08628605, -1.15990489, -0.60629728,  0.87379659,
        2.37278518, -0.21442972, -0.62014627,  0.44708072, -0.62194362])

In [130]:
arr=np.arange(25)

In [5]:
import numpy as np
import pandas as pd
lables=['a','b','c']
my_array=[10,20,30]
pd.Series(data=my_array)

0    10
1    20
2    30
dtype: int64

In [6]:
import numpy as np
import pandas as pd
lables=['a','b','c']
my_array=[10,20,30]
pd.Series(data=my_array,index=lables)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(my_array,lables)

a    10
b    20
c    30
dtype: int64

In [8]:
d={'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series([sum,len,print])


0      <built-in function sum>
1      <built-in function len>
2    <built-in function print>
dtype: object

In [23]:
d={'usa':1,'russia':2,'london':3,'newzealand':4}
ser1=pd.Series(d)

In [14]:
d['usa']

1

In [16]:
s={'usa':1,'russia':2,'london':3,'england':4}

In [1]:
ser2=pd.Series(s

NameError: name 'pd' is not defined

In [25]:
ser1+ser2

NameError: name 'scr2' is not defined

In [2]:
import numpy as np
import pandas as pd
lables=['a','b','c']
my_array=[10,20,30]
pd.Series(data=my_array,index=lables)


a    10
b    20
c    30
dtype: int64

In [1]:
d={'usa':1,'russia':2,'london':3,'newzealand':4}
ser1=pd.Series(d)

NameError: name 'pd' is not defined

In [1]:
s={'usa':1,'russia':2,'london':3,'england':4}

In [2]:
import pandas as pd
ser2=pd.Series(s)